Repository Battlebee12/LogicLegends, pull requests merged in 2024-03, with the labels that each got.

#70 all issues sorted
  event_ticketing/package-lock.json
  event_ticketing/package.json
  event_ticketing/src/AdminEvents.js
  event_ticketing/src/AdminLogin.js
  event_ticketing/src/AdminSignup.js
  event_ticketing/src/App.js
  event_ticketing/src/Signup.js
  event_ticketing/yarn.lock
Labels: backend

#72 front-end-testing
  event_ticketing/backend/database.js
  event_ticketing/cypress.config.ts
  event_ticketing/cypress/e2e/Homepage.cy.ts
  event_ticketing/cypress/e2e/event_detail.cy.ts
  event_ticketing/cypress/e2e/register_test.cy.ts
  event_ticketing/cypress/e2e/spec.cy.ts
  event_ticketing/cypress/fixtures/example.json
  event_ticketing/cypress/support/commands.ts
  event_ticketing/cypress/support/e2e.ts
  event_ticketing/package-lock.json
  event_ticketing/package.json
  event_ticketing/src/Eventlist.js
  event_ticketing/src/Navbar.js
  event_ticketing/src/Organize.js
  event_ticketing/src/about.js
  event_ticketing/src/components/searchBar.jsx
  event_ticketing/tsconfig.json
  event_ticketing/yarn.lock
Labels: Testing

#73 mostly finished implementing the frontend of admin event aproval
  event_ticketing/src/AdminEvents.js
  event_ticketing/src/AdminLogin.js
  event_ticketing/src/App.js
Labels: ui

#87 minor bug fix
  event_ticketing/src/Signup.js
Labels: bug, enhancement, Front end
