Repository Battlebee12/LogicLegends, pull requests merged in 2024-04, with the labels that each got.

#93 all issues dealt with
  event_ticketing/backend/index.js.zip
  event_ticketing/src.zip
  event_ticketing/src/AdminLogin.js
Labels: review

#102 Automation testing.
  backend/index.js
Labels: Testing

#105 Cart and conformation is working
  src/Cart.js
Labels: Front end, ui

#118 Contact us
  .env
  backend/index.js
  node_modules/.package-lock.json
  package-lock.json
  package.json
  src/Eventlist.js
  src/Images/educational.jpg
  src/Images/holi.jpg
  src/Images/music_concert.jpg
  src/Images/sports.jpg
  src/Navbar.js
  src/components/eventGrid.jsx
  src/contact.js
  yarn.lock
Labels: design, Front end, backend, ui
